### ISSUE TITLE
How blender generates synthetic data in onepose

### ISSUE THREAD

**Issue by lgq-gpu** [siatheindochinese/siatheindochinese#1]
Hello, first of all thank you for sharing your code, I am very interested in your code, but I have not touched blender, can you tell me how you collected the synthetic data with blender, thank you again. (Sorry, I didn't find an entry to ask a question on your onepose posting page, so I took the liberty to post a question on your homepage)

**Comment by siatheindochinese** [comment]
My method is tedious since I wrote the rendering manually in blender. I do not recommend it and I won't share the python scripts for it. You're better off using something like BlenderProc2 so you don't have to manually do what I did; I will be ditching my own code in favour for BlenderProc2.

**Comment by lgq-gpu** [comment]
Ok, thanks for your reply, I am also using blenderproc2 to render the data
